### ISSUE TITLE
HA 2022.12.0 onwards does not support anymore the scrape syntax used by HA MET Malaysia

### ISSUE THREAD

**Issue by pwickie** [zubir2k/HomeAssistantMETMalaysia#1]
HI there, firstly many thanks for sharing your code!!! it has been very useful.

Recently, HA has started flagging the error warning below. Wondering if there is any help available to update the HA MET Malaysia code to support the new HA syntax for scrape.

Thanks in advance.

HA ERROR MESSAGE :

The Scrape YAML configuration has been moved
This stops working in version 2022.12.0. Please address before upgrading.
Configuring Scrape using YAML has been moved to integration key.

Your existing YAML configuration will be working for 2 more versions.

Migrate your YAML configuration to the integration key according to the documentation.

**Comment by zubir2k** [comment]
Hi

Thank you for highlighting. Yes I am aware on the changes going to happened to the scrape integration and was planning to move away from it as there was a major change happened at MET Malaysia website thus impacting the scrape sensor not able to pull the required info (humidity). To overcome this, I use wttr.in information to fill in the gaps that MET API does not provide. 

I have updated this template to adopt the package method similar like the adzan repo. 
So far it is running ok in my test environment. Will try to update this repo soon.

**Comment by zubir2k** [comment]
@pwickie I have made the changes as explained earlier.
